package byit.aladdin.report.bo;


// Generated 2015-9-16 19:51:14 by Hibernate Tools 3.4.0.CR1
/**
 * IdaPmMenu generated by hbm2java
 */
public class IdaPmReportMenuBo{
	private String menuid;
	private String menuparent;
	private String menuname;
	private Long seq;
	private String menudesp;
	private String rem;
	private String state;
	private String url;
	private String _parentId;
	private String menuParentName;
	private Long ordinal;//排序
	public IdaPmReportMenuBo(String menuid, String menuparent, String menuname, Long seq, String menudesp, String rem,
			String state, String url, String _parentId, String menuParentName) {
		super();
		this.menuid = menuid;
		this.menuparent = menuparent;
		this.menuname = menuname;
		this.seq = seq;
		this.menudesp = menudesp;
		this.rem = rem;
		this.state = state;
		this.url = url;
		this._parentId = _parentId;
		this.menuParentName = menuParentName;
	}
	
	public Long getOrdinal() {
		return ordinal;
	}

	public void setOrdinal(Long ordinal) {
		this.ordinal = ordinal;
	}

	public IdaPmReportMenuBo() {
		super();
	}
	public String getMenuid() {
		return menuid;
	}
	public void setMenuid(String menuid) {
		this.menuid = menuid;
	}
	public String getMenuparent() {
		return menuparent;
	}
	public void setMenuparent(String menuparent) {
		this.menuparent = menuparent;
	}
	public String getMenuname() {
		return menuname;
	}
	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}
	public Long getSeq() {
		return seq;
	}
	public void setSeq(Long seq) {
		this.seq = seq;
	}
	public String getMenudesp() {
		return menudesp;
	}
	public void setMenudesp(String menudesp) {
		this.menudesp = menudesp;
	}
	public String getRem() {
		return rem;
	}
	public void setRem(String rem) {
		this.rem = rem;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String get_parentId() {
		return _parentId;
	}
	public void set_parentId(String _parentId) {
		this._parentId = _parentId;
	}
	public String getMenuParentName() {
		return menuParentName;
	}
	public void setMenuParentName(String menuParentName) {
		this.menuParentName = menuParentName;
	}
	@Override
	public String toString() {
		return "IdaPmReportMenuBo [menuid=" + menuid + ", menuparent=" + menuparent + ", menuname=" + menuname
				+ ", seq=" + seq + ", menudesp=" + menudesp + ", rem=" + rem + ", state=" + state + ", url=" + url
				+ ", _parentId=" + _parentId + ", menuParentName=" + menuParentName + "]";
	}
	
	
}
